background_opacity: 0.9
shell:
  program: /usr/bin/zsh
  args:
    - --login
font:
  size: 12
  offset:
    x: 0
    y: 8
  normal:
    family: Victor Mono
    style: SemiBold
  bold:
    family: Victor Mono
    style: Bold
  italic:
    family: Victor Mono
    style: Italic
window:
  decorations: none
cursor:
  style: Block
key_bindings:
  - key: V
    mods: Command
    action: Paste
  - key: C
    mods: Command
    action: Copy
selection:
  semantic_escape_chars: ",â”‚`|:\"' ()[]{}<>"
  save_to_clipboard: true
colors:
  primary:
    background: "#011627"
    foreground: "#acb4c2"
  cursor:
    text: "#fafafa"
    cursor: "#9ca1aa"
  selection:
    text: "#080808"
    background: "#b2ceee"
  normal:
    black: "#1d3b53"
    red: "#fc514e"
    green: "#a1cd5e"
    yellow: "#e3d18a"
    blue: "#82aaff"
    magenta: "#c792ea"
    cyan: "#7fdbca"
    white: "#a1aab8"
  bright:
    black: "#7c8f8f"
    red: "#ff5874"
    green: "#21c7a8"
    yellow: "#ecc48d"
    blue: "#82aaff"
    magenta: "#ae81ff"
    cyan: "#7fdbca"
    white: "#d6deeb"
